[book]
authors = ["josh rotenberg"]
language = "en"
src = "src"
title = "adrs documentation"

[output.html]
default-theme = "navy"
site-url = "/adrs-book/"
git-repository-url = "https://github.com/joshrotenberg/adrs/tree/main/book"
edit-url-template = "https://github.com/joshrotenberg/adrs/edit/main/book/{path}"

[output.html.fold]
enable = true

# Lint is run manually: mdbook-lint book/src
# [preprocessor.lint]
# command = "mdbook-lint"
# renderer = ["html"]
